version: '1'

services:
  warehouse:
    image: postgres:14
    container_name: warehouse
    environment:
      POSTGRES_USER: ${WAREHOUSE_USER}
      POSTGRES_PASSWORD: ${WAREHOUSE_PASSWORD}
      POSTGRES_DB: ${WAREHOUSE_DB}
    volumes:
      - ./containers/warehouse:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${WAREHOUSE_USER}" ]
      interval: 5s
      retries: 5
    restart: always
    ports:
      - "5432:5432"
    networks:
      - sfl_network

  loader:
    image: loader
    container_name: loader
    build:
      context: ./containers/loader/
    volumes:
      - ./:/opt/sfl
    environment:
      WAREHOUSE_USER: ${WAREHOUSE_USER}
      WAREHOUSE_PASSWORD: ${WAREHOUSE_PASSWORD}
      WAREHOUSE_DB: ${WAREHOUSE_DB}
      WAREHOUSE_HOST: ${WAREHOUSE_HOST}
      WARREHOUSE_PORT: ${WAREHOUSE_PORT}
    networks:
      - sfl_network

networks:
  sfl_network:
    name: sfl_network
